- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Include OADP operator role
      ansible.builtin.include_role:
        name: ../roles/enable-oadp-operator
    - name: Include OADP storage role
      ansible.builtin.include_role:
        name: ../roles/enable-oadp-object-storage
    - name: Include Hub backup role
      ansible.builtin.include_role:
        name: ../roles/enable-hub-backup
