- hosts: localhost
  connection: local
  become: false
  tasks:
  - name: Include role
    ansible.builtin.include_role:
      name: ../roles/connect-aks-to-acm-hub
  - name: Include role
    ansible.builtin.include_role:
      name: ../roles/import-managedcluster-default-invoke
