- name: "Create kubeconfig directory if does not exist"
  ansible.builtin.file:
    path: ../kubeconfig
    state: directory
- name: "Generate Kubeconfig file"
  ansible.builtin.template:
    src: ../roles/k8s-cluster-access/templates/kubeconfig.yml
    dest: "../kubeconfig/{{ hostvars[inventory_hostname].cluster_name }}"
